name: BuildingAssister
main: io.github.nickacpt.buildingassister.BuildingAssisterPlugin
version: 1.0.0-SNAPSHOT
api-version: 1.17

permissions:
  buildingassister.use:
    default: op
    description: "Allows players to use BuildingAssister"

commands:
  mirror:
    permission: buildingassister.use
    permission-message: "You are not allowed to use this."